<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AcceptChangeRequestByCustomer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0174e69c-eaf1-478b-ae5c-7762a784d894</testSuiteGuid>
   <testCaseLink>
      <guid>ec1d76fb-4fc6-4778-90a0-0e4d0e0bfaa1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/PlaceOrderBySearchTestMode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75feb689-f7b4-4496-ac8a-209a3f3bb39e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd8abdd4-bde1-4e64-834f-330859275c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177f70e0-8005-455e-a090-a5b1e214728a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f1c32dd-5f19-4880-9fb4-6c5bc266787e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/New Booking Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09f041f2-0973-4881-a2df-e56f3e3e79a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3dc0808-22ed-4034-bbd1-7630291b4efb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b05fc562-9327-4190-9100-404cc595132a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8031ebc-4ef8-413f-8062-0391f9c05fc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/InboxSubmitChanges</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d76f2a4-881f-461f-91a8-7b8dcb68b572</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f66cd05-eb20-4900-8ed9-33dc6777d504</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>605299db-ec82-4584-a3a4-e71780a649fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/AcceptChanges</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9011369-14f8-48d5-ab34-8b5e989c6400</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34678717-5eff-42cf-8b53-2838d0b3d8ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd0c3846-0682-4289-b617-3c39fbbd4a9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/InboxAcceptOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>844fff69-cc51-4434-9368-b67cf9ea7a03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac6f74c6-83b4-4a25-8593-725b12b7c7fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>492581e9-31c8-4dd2-8a01-f4179d6ef672</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/TaskCompleted</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76838a76-16a0-429e-80a8-586fc8e5a42e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3394817-7f84-4164-847e-12a4352b6ff8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adc0cf56-ba55-4205-9469-d4da7705c568</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerInbox</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>904be319-495e-4589-91c0-ef07721d6d8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>305b3af4-cc9b-42af-b118-206d98af21d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9809803a-b3ac-4155-8a01-a48f9d518182</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/Order Completed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f47004-bea7-4a61-8c12-92462a2311cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5b3c1dc-e763-46f2-bff3-03e879a72f0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae937c1-a254-4a18-915e-c2e1f52f72d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60215496-dd0c-47ee-8541-feffee38b90a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerOrderCompletedOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1685701a-9693-4cfd-ae41-fe9274b953c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eff84ee-0cbf-4c73-aa62-0cb4e4a35e0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>02ab188c-95ff-46fa-ab70-c96e8b9b5e99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/TransactionHistory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af27d5d5-6687-465e-a06a-ab83561a312e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e1da3e5-b620-449a-ace0-04df03d9809f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
