<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompleteBookings on Live Mode</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a665b71f-9f3c-4e77-b3ed-d954b298f7dc</testSuiteGuid>
   <testCaseLink>
      <guid>285c18a8-510a-42c2-a534-3915a64997b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/PlaceOrderBySearchTestMode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75feb689-f7b4-4496-ac8a-209a3f3bb39e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd8abdd4-bde1-4e64-834f-330859275c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177f70e0-8005-455e-a090-a5b1e214728a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6adc8e0a-f621-4138-9eb9-9beedd065bf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/New Booking Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09f041f2-0973-4881-a2df-e56f3e3e79a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3dc0808-22ed-4034-bbd1-7630291b4efb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b05fc562-9327-4190-9100-404cc595132a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe8fa1df-4a28-49e9-9568-e27f5466fa9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/InboxAcceptOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>844fff69-cc51-4434-9368-b67cf9ea7a03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac6f74c6-83b4-4a25-8593-725b12b7c7fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c414cf4-24de-4750-ba1e-04c404dec1c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/InboxVerifyMessageDetail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99f47c57-9b5a-442b-aaa4-da1a221e2f04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ea91378-0fb4-4ded-8423-1d0f940e421b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff233c2d-130e-4a21-82ae-f4eccc05b3a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/AcceptedOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b11cc136-1577-46bc-8b12-0bb3f662bc6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>875fc201-796f-4275-96fc-652c4f8b9586</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb98e6a1-8488-4a5a-a659-56c6ba184505</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerAcceptedRequestedOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00ce5357-46ce-4b4a-9faf-9fd40d4cb726</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c6ec1c6-5ca5-49b5-b89e-76623d89e73c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abe05382-8d5d-41a5-a3d6-91f3200c0fff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerInbox</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>904be319-495e-4589-91c0-ef07721d6d8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>305b3af4-cc9b-42af-b118-206d98af21d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72953a37-2adf-4d82-92b0-a9f9df39a26b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/TaskCompleted(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76838a76-16a0-429e-80a8-586fc8e5a42e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3394817-7f84-4164-847e-12a4352b6ff8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e98c217-8000-4605-aa93-e5479f2aee18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/Order Completed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f47004-bea7-4a61-8c12-92462a2311cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5b3c1dc-e763-46f2-bff3-03e879a72f0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae937c1-a254-4a18-915e-c2e1f52f72d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1645f0ed-237c-4b31-85f3-9b9961d9aa19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerOrderCompletedOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1685701a-9693-4cfd-ae41-fe9274b953c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eff84ee-0cbf-4c73-aa62-0cb4e4a35e0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6d26f2e-c840-4c00-a0f1-b76d05029dfb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/TransactionHistory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af27d5d5-6687-465e-a06a-ab83561a312e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e1da3e5-b620-449a-ace0-04df03d9809f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
