<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DeclineChangeRequestByCustomer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>eb79771e-c951-4401-9c1e-db8cd7c15930</testSuiteGuid>
   <testCaseLink>
      <guid>ec1d76fb-4fc6-4778-90a0-0e4d0e0bfaa1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/PlaceOrderBySearchTestMode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75feb689-f7b4-4496-ac8a-209a3f3bb39e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd8abdd4-bde1-4e64-834f-330859275c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177f70e0-8005-455e-a090-a5b1e214728a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f1c32dd-5f19-4880-9fb4-6c5bc266787e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/New Booking Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09f041f2-0973-4881-a2df-e56f3e3e79a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3dc0808-22ed-4034-bbd1-7630291b4efb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b05fc562-9327-4190-9100-404cc595132a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8031ebc-4ef8-413f-8062-0391f9c05fc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/InboxSubmitChanges</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d76f2a4-881f-461f-91a8-7b8dcb68b572</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f66cd05-eb20-4900-8ed9-33dc6777d504</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7f559af-fbfb-4a54-ae31-3a516d86caeb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/RejectChanges</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01aec915-76c0-4faf-8252-58522c54193f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e57c9bf-fbe5-4d14-9246-26db1dd674a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfc5bf4f-ab68-47fc-a384-9a7218f077b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/Customer Decline Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1f96cb2-b6bf-4b87-827a-a1aee8b824a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc12ce97-fbae-41f0-9085-ab5e62df6171</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
