<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RejectOrderByServiceProvider</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3e711a2a-94e5-42fb-9978-0a2888f0b5fc</testSuiteGuid>
   <testCaseLink>
      <guid>b517c79a-b33a-4809-871d-df83a66180cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/PlaceOrderBySearchTestMode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75feb689-f7b4-4496-ac8a-209a3f3bb39e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd8abdd4-bde1-4e64-834f-330859275c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177f70e0-8005-455e-a090-a5b1e214728a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>15e22870-431a-4c42-9f24-f38ce7c6f8af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/New Booking Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09f041f2-0973-4881-a2df-e56f3e3e79a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3dc0808-22ed-4034-bbd1-7630291b4efb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b05fc562-9327-4190-9100-404cc595132a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2f61db1-b090-4460-92a6-cd690aad0231</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/InboxRejectOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1957adad-048f-460d-814e-65cd6ba46e23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64174dce-fc4b-4f83-8839-94422fbb002b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f5a96c5-db3a-4396-a1f5-5b4e968f464a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/InboxVerifyMessageDetail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99f47c57-9b5a-442b-aaa4-da1a221e2f04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ea91378-0fb4-4ded-8423-1d0f940e421b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e828050-bc93-4a09-9156-4d3f5a712aa8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/Order Declined</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06ef2198-6e4f-466e-8eea-5abbecf2b30f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd0c776b-df00-4835-ae90-844633772fbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2859043b-34f4-4292-8511-88ed1d5c04b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/Customer Decline Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1f96cb2-b6bf-4b87-827a-a1aee8b824a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc12ce97-fbae-41f0-9085-ab5e62df6171</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c36b65fe-2036-4f51-b8b8-b050e80b601a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerInbox</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>904be319-495e-4589-91c0-ef07721d6d8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>305b3af4-cc9b-42af-b118-206d98af21d7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
