<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ServiceProivderSignUp</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b6347288-a90c-4f40-a0be-6ab4916d3ed3</testSuiteGuid>
   <testCaseLink>
      <guid>e2f5e744-90b5-417e-b02a-9ed5d44fcd27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Sign Up/RegistrationValidation/InvalidEmailIdLogin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d28d4edc-70c4-4d5f-bbe1-64ef7054adac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33dba286-4443-4124-b97a-92d5c3ed721f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7638825f-5d62-44fe-b3cc-2b636938fe23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Sign Up/RegistrationValidation/InvalidPwdLogin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76fe9314-64f2-4602-8a4a-692ab7106faf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c841b2-4abf-4e11-a557-97e57ff4f296</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>901c2d4d-4953-4f2c-b01b-8e96eb8a4831</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Sign Up/RegistrationValidation/SignUpBlankValidation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6e50168-f926-4412-a116-1d0115ae7d7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfd40bd6-cc6a-43b6-b490-1ceb7db5cd6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>588a4272-f0b4-43d1-b2b5-1a06ca473100</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Sign Up/RegistrationValidation/SignUpValidationInvalidContact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e75fcb7-0342-4516-949c-f3e3280085cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6683e9e2-48fb-4dcc-9e68-44cf4537a405</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a9a070d-89d5-42e1-a0f0-a49f88ece9ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Sign Up/RegistrationValidation/SignUpValidationInvalidEmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0c02e09-6451-484a-ac70-ebdb32c35d63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13103019-ddb2-43cf-a88c-c8aef3c2f154</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e054f6e-f90d-4864-ad9d-7a85adedf009</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Sign Up/RegistrationValidation/SignUpValidationInvalidFirstLastName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e057eb2-bb75-4090-8815-34d05f6fbd4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e2193e1-adc8-4ff3-8390-d83bc40b6a5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4fc854cb-0832-4f6b-a83c-22d3a66cdf64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Sign Up/RegistrationValidation/SignUpValidationInvalidPWD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af3f8fb9-c963-4648-abbe-dd8093fa304b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7211ecc1-86a0-45c2-b87b-a399d3800e06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ece16910-2b21-4766-9e6d-3ef09f978735</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Sign Up/ServProvSignUp</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c06aaa2-26d7-43e5-b5ee-7f1ccc4ed925</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f80a3d4-e1c6-44e1-960f-2b5b6ce35642</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
