<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ViewNewAcceptCancelAllBookingByCustomers</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a916c14e-6a4e-4a9d-832a-b960f27c530e</testSuiteGuid>
   <testCaseLink>
      <guid>1ed145b7-6ee2-45db-84ba-c31d0e8ce216</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerNewOrder(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd81110-bc9a-4ad1-be46-e833ed250e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>742d84cb-2ef2-4acd-89f6-79d9d6195c9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee9afc22-c454-4eeb-bc49-bfd11244c950</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerALLOrders(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c82a4be1-545f-4fdc-b776-44d4b146e87b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b00f44-8349-4652-8ad5-cfed5e0287cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78a6b997-0277-4529-97ea-7672339af61a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerAcceptedRequest(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcd80e62-5295-48bb-87db-2a035b202181</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0e4f894-0a5c-4e20-aa8e-ad08249422f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>baa89239-93e8-4d03-86eb-96c675461c09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CancelOrder(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d42577b-3904-4865-b8b6-2207b167150c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b13e0b-3c20-492e-a883-ecfa02d592b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8507b69-0057-43e5-8340-a2560a1764b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerDeclined(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0105cbe-ff79-425a-a9b0-21444606efc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b292d13e-257e-4f59-b5f0-42afa11e883b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f287091-dd69-4cd0-b21a-4de3f6ec9d45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/Customer/CustomerOrderCompleted(ALL)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faec3000-cfe3-490e-a279-5c054542fe80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b347433-3b98-4d08-ae01-ec37eb73022a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
