<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ViewNewAcceptCancelAllBookingByServiceProviders</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d5b37827-bff2-483d-bdef-3c3dc376d557</testSuiteGuid>
   <testCaseLink>
      <guid>368ad5c9-b2df-418c-8709-340e47b53067</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/NewBookingOrder(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5caca130-4719-46f3-b35c-3c4ab934b82b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd78769c-aeb7-4fc1-bee6-a5378117896d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93a80df6-845b-4bf2-9278-0b74859d083e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/AcceptedOrder(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf6523ee-af52-41d5-a1d4-8a65077a8246</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d47579a-64e6-4c33-95e3-8dc44a4d939e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d4ef603-e26c-445d-8efd-9a51734c7283</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/ALLorder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d33eda-4252-4b68-9821-91d942a98005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eaba369-c8ae-4fdf-b871-1aafeae08e2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1064eda-612c-4bd5-809b-bd46313ade72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/InboxVerifyMessageDetail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99f47c57-9b5a-442b-aaa4-da1a221e2f04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ea91378-0fb4-4ded-8423-1d0f940e421b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b546d3c2-91b9-4f78-b3d2-570b7dbdc20e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/OrderCompleted(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a4be702-3b77-4aac-9a6f-74bca752a9aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a70844f9-f174-4d92-be92-5cbac794c7a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f37bd77-67f6-430e-9b18-2660b832efaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Workilo/Bookings/ServiceProvider/OrderDeclined(All)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>444526d2-68a1-4e95-b340-82b9a3c3735c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a147de7-4e24-4699-b60c-c15023b41e9a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
